In [1]:
import sys
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])

In [4]:
b = np.array([0,.5,1,1.5,2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [12]:
b[[0, 2, -1]]

array([0., 1., 2.])

In [13]:
a

array([1, 2, 3, 4])

In [14]:
a.dtype

dtype('int32')

In [15]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
b.dtype

dtype('float64')

In [18]:
np.array([1,2,3,4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [22]:
c = np.array(['a', 'b', 'c'])

In [23]:
c.dtype

dtype('<U1')

In [25]:
d = np.array([{'a':1}, sys])

In [26]:
d.dtype

dtype('O')

In [30]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [31]:
A.shape

(2, 3)

In [32]:
A.ndim

2

In [33]:
A.size

6

In [34]:
B = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [35]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [36]:
B.shape

(2, 2, 3)

In [37]:
B.ndim

3

In [38]:
B.size

12

In [40]:
C = np.array([
    [        
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4]
    ]
]) 
#dimensions must match

C:\Users\Rares\AppData\Local\Temp\ipykernel_19136\542198437.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [42]:
C.dtype

dtype('O')

In [43]:
C.shape

(2,)

In [44]:
C.size

2

In [46]:
#Square matrix
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [47]:
A[1]

array([4, 5, 6])

In [48]:
A[1][0]

4

In [49]:
A[1,0]

4

In [50]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [52]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [53]:
A[:2,2:]

array([[3],
       [6]])

In [54]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
A[1] = np.array([10,10,10])

In [56]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [57]:
A[2] = 99

In [58]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [59]:
#Statistics functions

In [60]:
a = np.array([1,2,3,4])

In [62]:
a.sum()

10

In [63]:
a.mean()

2.5

In [73]:
a.std()
#standard deviation

1.118033988749895

In [65]:
a.var()

1.25

In [66]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [67]:
A.sum()

45

In [68]:
A.mean()

5.0

In [69]:
A.std()

2.581988897471611

In [70]:
A.sum(axis=0)

array([12, 15, 18])

In [72]:
A.sum(axis=1)

array([ 6, 15, 24])

In [74]:
A.sum(axis=-1)

array([ 6, 15, 24])

In [91]:
#Broadcasting and Vectorized operations

In [77]:
a = np.arange(4)

In [78]:
a

array([0, 1, 2, 3])

In [79]:
a + 10

array([10, 11, 12, 13])

In [80]:
a * 10

array([ 0, 10, 20, 30])

In [81]:
a

array([0, 1, 2, 3])

In [82]:
a += 100

In [83]:
a

array([100, 101, 102, 103])

In [84]:
l = [0,1,2,3]

In [85]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [86]:
a = np.arange(4)

In [87]:
a

array([0, 1, 2, 3])

In [88]:
b = np.array([10,10,10,10])

In [89]:
a + b

array([10, 11, 12, 13])

In [90]:
a * b

array([ 0, 10, 20, 30])

In [92]:
#Boolean arrays

In [93]:
a = np.arange(4)

In [94]:
a

array([0, 1, 2, 3])

In [95]:
a[[0,-1]]

array([0, 3])

In [96]:
a[[True, False, False, True]]

array([0, 3])

In [97]:
a >= 2

array([False, False,  True,  True])

In [98]:
a[a>=2]

array([2, 3])

In [99]:
a.mean()

1.5

In [100]:
a[a > a.mean()]

array([2, 3])

In [103]:
a[~(a > a.mean())]
# ~ - negation 

array([0, 1])

In [109]:
A = np.random.randint(100, size=(3,3))

In [110]:
A

array([[25, 18, 17],
       [59, 70, 28],
       [86, 27, 44]])

In [111]:
A > 30

array([[False, False, False],
       [ True,  True, False],
       [ True, False,  True]])

In [113]:
A[A>30]

array([59, 70, 86, 44])

In [114]:
#Linear ALgebra

In [115]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [116]:
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [118]:
A.dot(B)
# Dot product

array([[20, 14],
       [56, 41],
       [92, 68]])

In [123]:
A @ B
#matrix multipication

array([[20, 14],
       [56, 41],
       [92, 68]])

In [120]:
B.T
#transpose

array([[6, 4, 2],
       [5, 3, 1]])

In [121]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [124]:
#Size of objects in Memory

In [126]:
#An integer in Python is > 24 bytes
sys.getsizeof(1)

28

In [128]:
#Longs are even larger
sys.getsizeof(10**100)

72

In [133]:
#NumPy is much smaller in size
np.dtype(int).itemsize

4

In [131]:
np.dtype(float).itemsize

8

In [134]:
#Performance

In [135]:
l = list(range(1000))

In [136]:
a = np.arange(1000)

In [137]:
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 0 ns


332833500

In [138]:
%time sum([x ** 2 for x in l])

CPU times: total: 0 ns
Wall time: 4 ms


332833500